import { useState } from 'react';
import { checkPorts, hasInput, hasOutput, type Port, type ShowSnapshot, type Node, type Crosspoint } from '@comms/protocol';
import { api } from './api.ts';
import { Head, Field, label, activeRoutes, gateText, TYPE_LABEL, opensMic } from './common.tsx';
type Props = { state: ShowSnapshot; onOpen(id: string, route?: Crosspoint): void; onError(s: string): void };
export function Matrix({ state, onOpen }: Omit<Props, 'onError'>) {
  const sources=state.ports.filter(hasInput),destinations=state.ports.filter(hasOutput),active=activeRoutes(state);
  return <><Head title="Matrix" sub="Routes derived from functions. Select a cell to edit the port that owns it."/><div style={{overflow:'auto'}}><table className="pt matrix-table"><thead><tr><th>Source → destination</th>{destinations.map(p=><th key={p.id}>{p.label}</th>)}</tr></thead><tbody>{sources.map(p=><tr key={p.id}><th>{p.label}</th>{destinations.map(d=>{const routes=state.crosspoints.filter(x=>x.source===p.id&&x.destination===d.id);return <td key={d.id}>{routes.map((x,i)=><button key={i} className={`cell ${active.has(x)?'active':''}`} title={`${gateText(x.gate)} · ${x.level} dB · set on ${label(state,x.owner)}`} onClick={()=>onOpen(x.owner, x)}>{x.role==='program'?'P':x.role==='interrupt'?'I':x.gate==='always'?'A':x.gate.trigger.kind==='key'?`K${x.gate.trigger.key}`:gateText(x.gate)}</button>)}{!routes.length&&<span className="dim">·</span>}</td>;})}</tr>)}</tbody></table></div><p className="muted">A = Always · K = Key · P = Program · I = Interrupt. Groups expand to their members. Parallel routes carry each source once, at the highest active gain after IFB dim.</p></>;
}
export function Groups({ state, onOpen, onError }: Props) {
  const [selected,setSelected]=useState(''),[member,setMember]=useState('');
  const virtual=state.ports.filter(p=>['conference','group','ifb'].includes(p.type));const p=virtual.find(p=>p.id===selected)??virtual[0];
  const incoming=state.crosspoints.filter(x=>x.destination===p?.id),outgoing=state.crosspoints.filter(x=>x.source===p?.id);
  const add=async()=>{if(!p||!member)return;try {
    if(p.type==='group'){await api.updatePort({...p,group:{members:[...new Set([...(p.group?.members??[]),member])]}});}
    else {
      const source=structuredClone(state.ports.find(s=>s.id===member)!);
      if(source.triggers.some(t=>t.functions.some(f=>f.fn==='callToConference'&&f.conf===p.id||f.fn==='callToIFB'&&f.ifb===p.id)))throw new Error('This port is already a member. Open its port to edit the function.');
      const f=p.type==='conference'?{fn:'callToConference' as const,conf:p.id}:{fn:'callToIFB' as const,ifb:p.id};
      if(source.type==='station'){
        const key=[1,2,3,4,5,6].find(n=>!source.triggers.some(t=>t.kind==='key'&&t.key===n));
        if(!key)throw new Error('This station already has six keys. Open its port to choose a trigger.');
        source.triggers.push({kind:'key',key,mode:'ptt',functions:[f]});
      }else{let t=source.triggers.find(t=>t.kind==='always');if(!t){t={kind:'always',functions:[]};source.triggers.push(t);}t.functions.push(f);}
      await api.updatePort(source);
    }
    setMember('');
  }catch(e){onError((e as Error).message);}};
  return <><Head title="Groups & conferences" sub="Membership comes from each port’s functions. Adding a station assigns a key; hardware gets a standing function." action={<button className="btn primary" onClick={()=>onOpen('new')}>New port</button>}/><div className="gc"><div className="list">{virtual.map(p=><button className={`item ${selected===p.id?'on':''}`} key={p.id} onClick={()=>setSelected(p.id)}><span className={`sw ${p.type}`}/>{p.label}<small> {TYPE_LABEL[p.type]}</small></button>)}</div>{p?<div className="editor"><h2>{p.name}</h2><button className="btn" onClick={()=>onOpen(p.id)}>Edit {p.label}</button><table className="pt"><thead><tr><th>Port</th><th>Role</th><th>When</th><th>Owner</th></tr></thead><tbody>{[...incoming,...outgoing].map((x,i)=><tr key={i}><td>{label(state,x.destination===p.id?x.source:x.destination)}</td><td>{x.role==='program'?'Program':x.role==='interrupt'?'Interrupt':x.destination===p.id?'Talk':'Listen'}</td><td>{gateText(x.gate)}</td><td><button onClick={()=>onOpen(x.owner, x)}>Open {label(state,x.owner)}</button></td></tr>)}{p.group?.members.map(id=><tr key={id}><td>{label(state,id)}</td><td>Member</td><td>While called</td><td><button onClick={()=>onOpen(p.id)}>Edit group</button></td></tr>)}</tbody></table><div className="toolbar"><select className="sel" style={{width:240}} aria-label="New member" value={member} onChange={e=>setMember(e.target.value)}><option value="">Choose a port</option>{state.ports.filter(q=>p.type==='group'?['station','output'].includes(q.type):p.type==='ifb'?['station','input'].includes(q.type):['station','input','output'].includes(q.type)).map(q=><option key={q.id} value={q.id}>{q.label}</option>)}</select><button className="btn" disabled={!member} onClick={()=>void add()}>Add member</button></div></div>:<p className="nothing">Create a conference, group or IFB in Ports.</p>}</div></>;
}
function NodeEditor({ node, state, onOpen, onError }: { node: Node } & Props) {
  const [draft,setDraft]=useState(()=>structuredClone(node)),[busy,setBusy]=useState(false);
  const save=async()=>{setBusy(true);try{await api.updateNode(node.id,{name:draft.name,inputs:draft.inputs,outputs:draft.outputs});}catch(e){onError((e as Error).message);}finally{setBusy(false);}};
  return <section className="card"><div className="ch"><b>{node.name}</b><span className={`dot ${state.ports.some(p=>p.hardware?.nodeId===node.id&&state.live[p.id]?.connected)?'':'off'}`}/></div><small className="muted">{node.address} · Last seen {new Date(node.lastSeen).toLocaleTimeString()}</small>{(['inputs','outputs'] as const).map(dir=><section className="blk" key={dir}><h3>{dir==='inputs'?'Inputs':'Outputs'}</h3><table className="pt"><thead><tr><th>In use</th><th>Channel</th><th>Short name</th><th>Trim (dB)</th></tr></thead><tbody>{draft[dir].map((c,i)=><tr key={c.channel}><td><input aria-label={`${dir} ${c.channel} in use`} type="checkbox" checked={c.inUse} onChange={e=>{const next=structuredClone(draft);next[dir][i].inUse=e.target.checked;setDraft(next);}}/></td><td><button onClick={()=>{const p=state.ports.find(p=>p.hardware?.nodeId===node.id&&p.hardware.channel===c.channel&&p.type===(dir==='inputs'?'input':'output'));if(p)onOpen(p.id);}}>{c.name}</button></td><td><input className="in" aria-label={`${dir} ${c.channel} short name`} value={c.shortName??''} onChange={e=>{const next=structuredClone(draft);next[dir][i].shortName=e.target.value;setDraft(next);}}/></td><td><input className="in" style={{width:72}} aria-label={`${dir} ${c.channel} trim`} type="number" min={-24} max={24} step={0.5} value={c.trim} onChange={e=>{const next=structuredClone(draft);next[dir][i].trim=Number(e.target.value);setDraft(next);}}/></td></tr>)}</tbody></table></section>)}<button className="btn" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save channels'}</button></section>;
}
export function Hardware(props: Props) {return <><Head title="I/O nodes" sub="Select channels in use. Each channel gets its own input or output port."/><div className="cards">{props.state.nodes.map(n=><NodeEditor key={`${n.id}:${JSON.stringify([n.inputs,n.outputs])}`} node={n} {...props}/>)}</div>{!props.state.nodes.length&&<p className="nothing">No nodes registered. Run comms-node on the computer connected to your audio interface.</p>}</>;}
export function Live({ state, onOpen, levels }: Omit<Props,'onError'> & { levels: Record<string,number> }) {
  const issues=checkPorts(state.ports);const physical=state.ports.filter(p=>['station','input','output'].includes(p.type));
  for(const p of physical)if(!state.live[p.id]?.connected&&(p.hardware||p.triggers.some(t=>t.kind==='key')))issues.push({portId:p.id,message:p.hardware?'Node offline.':'Station offline with keys configured.',severity:'attention'});
  return <><Head title="Live" sub="Open keys, voice activity and incoming callers."/><div className="live"><table className="pt"><thead><tr><th>Port</th><th>Open now</th><th>Incoming</th><th>Last caller</th><th>Level</th></tr></thead><tbody>{physical.map(p=>{const s=state.live[p.id];return <tr key={p.id}><td><button onClick={()=>onOpen(p.id)}><span className={`dot ${s?.connected?'':'off'}`}/> {p.label}</button></td><td>{Object.entries(s?.keys??{}).filter(([,on])=>on).map(([key])=><span className={`badge${opensMic(p,key)?' hot':''}`} key={key}>{key==='reply'?'Reply':`Key ${key}`}</span>)}{s?.voxOpen&&<span className="badge">Vox</span>}</td><td>{s?.incoming.map(id=>label(state,id)).join(', ')||'—'}</td><td>{s?.lastCaller?label(state,s.lastCaller):'—'}</td><td><meter min={0} max={1} value={levels[p.id]??0} aria-label={`${p.label} level`}/></td></tr>;})}</tbody></table><aside className="rail"><section className="attn"><h2>Needs attention</h2>{issues.map((i,n)=><div className="it" key={n}><span className="dot warn"/><button onClick={()=>onOpen(i.portId)}>{label(state,i.portId)}<small>{i.message}</small></button></div>)}{!issues.length&&<p className="empty">Nothing needs attention.</p>}</section></aside></div></>;
}
